
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt


#dosya = pd.read_csv("vgsalesGlobale.csv")
#print(dosya)
#print("_"*50)
#
#print(dosya.head(10).to_string())
#print("_"*100)
#print(dosya.tail(10).to_string())
#print()
#print(dosya.shape)
#print()
#print(dosya.dtypes)
#print()
#print(dosya.isnull())
#print()
#print(dosya.notnull())
#print()
#print(dosya.isnull().sum())
#print()
#print(dosya.notnull().sum())
#print()
#print(dosya["Genre"].head())
#print()
#print(dosya["Name"].tail())
#print()
#print(dosya.columns)
#print()
#print(dosya.index)
#print()
#print(dosya[["Year", "Publisher"]].head(10))
#print()
#dosya.rename(columns={"Name": "ISIM", "Year": "YIL", "Genre": "TÜR", "Publisher": "yayin_evi"}, inplace=True)
#print(dosya.head(15).to_string())
#print()
#print(dosya.iloc[0])
#print()
#print(dosya.iloc[0, 3])
#print()
#print(dosya.iloc[5, 2:6])
#print()
#print(dosya.iloc[1:4, 4:7])
#print()
#print(dosya.iloc[0, [2, 3, 4]])
#print("_"*100)
#print(dosya.head(15).to_string())
#print()
#print(dosya.loc[14, "ISIM"])
#print()
#print(dosya.loc[3, ["TÜR", "yayin_evi"]])
#print()
#print(dosya.loc[2:5, "ISIM":"yayin_evi"])

dosya = pd.read_csv("vgsalesGlobale.csv")
#dosya.dropna(axis="columns", how="any", inplace=True)
print(dosya.head().to_string())
print()
print(dosya.Genre.value_counts())
print()
print(dosya[dosya.Genre == "Puzzle"]["NA_Sales"].value_counts(normalize=True).to_string())
print()
print(dosya.Publisher.value_counts().to_string())
print()
print(dosya.groupby("Publisher")["Name"].value_counts(normalize=True).head(20).to_string())
print("_"*5000)

vs = pd.read_csv("örnek dosya.csv")
print(vs.head().to_string())
print()
print(vs["Review Date"].str.slice(0, 4).value_counts().to_string())
print("\n")
print(vs["Country"].str.slice(0, 20).value_counts().to_string())
print("\n\n\n")

print(vs["Time"].value_counts())
print()

birlestir = vs["Review Date"].str.cat(vs["Time"], sep=" ")
vs["Tarih_Zaman"] = pd.to_datetime(birlestir)
print(vs["Tarih_Zaman"].head(10))
print()
print(vs.head(10).to_string())
print()
print(vs.dtypes)
print()
print(vs.loc[0:9, "City":"Tarih_Zaman"].to_string())
print()
print(vs.loc[0:9, ["Review Date", "Tarih_Zaman"]])
print()
print(vs.Tarih_Zaman.dt.month.head(10))
print()
print(vs["Tarih_Zaman"].dt.year.head(10))
print()
print(vs["Tarih_Zaman"].dt.day.head(10))
print()
print(vs["Tarih_Zaman"].dt.date.head(10))
print()
print(vs["Tarih_Zaman"].dt.second.head(10))
print()
print(vs["Tarih_Zaman"].dt.minute.head(10))
print()
print(vs["Tarih_Zaman"].dt.hour.head(10))
print("_"*200)

print(vs["City"].value_counts())
print(vs.dtypes)
print()
vs["City"] = vs["City"].astype(bool)
print(vs.dtypes)
print()
print(vs["City"])
print()
print(vs.loc[0:9, "Country":"Room Price"].head(10).to_string())
print()
print(vs["City"].value_counts())
print()
print(vs["City"].mean())
print()
print(vs.groupby(vs.Tarih_Zaman.dt.year)["Room Price"].mean())
print()
print(vs[["Tarih_Zaman", "Room Price"]].head(10))
print()
#print(vs[["Tarih_Zaman", "Room Price"]].head(10).plot(x="Tarih_Zaman", y="Room Price", kind="barh"))
#plt.show()
print("_"*50)

print(vs["Tarih_Zaman"].head(14))
print()
print(vs[["Tarih_Zaman", "Room Price"]].head(14))
print()
#print(vs[["Tarih_Zaman", "Room Price"]].head(14).plot(x="Tarih_Zaman", y="Room Price", kind="barh"))
#plt.show()

vs["Seneler"] = vs["Review Date"].str.slice(0, 4)
print(vs["Seneler"])
print()
print(vs["Seneler"].head(15))
print()
print(vs[["Seneler", "Room Price"]].head(15))
print()
print(vs.groupby("Seneler")["Room Price"].mean())
print()
vs["Seneler2"] = vs["Seneler"].head(15)
print(vs["Seneler2"].head(15))
print()
print(vs[["Seneler2", "Room Price"]].head(15))
print()
#print(vs[["Seneler2", "Room Price"]].head(10).plot(x="Seneler2", y="Room Price", kind="barh"))
#plt.show()
print(vs.groupby(vs.Tarih_Zaman.dt.year)["Room Price"].mean())
print()
print(vs[["Seneler2", "Room Price"]].head(15))
print()
print(vs.groupby(vs.Seneler2)["Room Price"].sum().head(15))
print()
print(vs.groupby(vs.Seneler2)["Room Price"].sum().head(15).plot(x="Seneler2", y="Room Price", kind="bar"))
plt.show()





